name: CICD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project with Maven
        env:
          SPRING_APP_NAME: ${{ secrets.SPRING_APP_NAME }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_DATASOURCE_DRIVER: ${{ secrets.SPRING_DATASOURCE_DRIVER }}
          SPRING_JPA_PLATFORM: ${{ secrets.SPRING_JPA_PLATFORM }}
          SPRING_JPA_DDL_AUTO: ${{ secrets.SPRING_JPA_DDL_AUTO }}
          VALIDATION_URL: ${{ secrets.VALIDATION_URL }}
          BALANCE_RECORD_API_URL: ${{ secrets.BALANCE_RECORD_API_URL }}
        run: mvn clean install
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'ntd_calculator-Operation'
          environment_name: 'Ntdcalculator-Operation-env'
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: target/ntd-calculator-operation-1.0.0.jar
