name: CICD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project with Maven
        run: mvn clean install \
          -Dspring.application.name=${{ secrets.SPRING_APP_NAME }} \
          -Dspring.datasource.url=${{ secrets.SPRING_DATASOURCE_URL }} \
          -Dspring.datasource.username=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
          -Dspring.datasource.password=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
          -Dspring.datasource.driver-class-name=${{ secrets.SPRING_DATASOURCE_DRIVER }} \
          -Dspring.jpa.database-platform=${{ secrets.SPRING_JPA_PLATFORM }} \
          -Dspring.jpa.hibernate.ddl-auto=${{ secrets.SPRING_JPA_DDL_AUTO }} \
          -Dvalidation.url=${{ secrets.VALIDATION_URL }} \
          -Dbalance-record.api.url=${{ secrets.BALANCE_RECORD_API_URL }}
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'ntd_calculator-Operation'
          environment_name: 'Ntdcalculator-Operation-env'
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: target/ntd-calculator-operation-1.0.0.jar
